variables:
  - name: System.Debug
    value: true

resources:
 repositories:
   - repository: MonoDroidSamples
     type: github
     name: xamarin/monodroid-samples
     #endpoint: v-mazayt-pat-new
     endpoint: github.com_max-zaytsev
   - repository: TestR
     type: github
     #endpoint: v-mazayt-pat-new
     endpoint: github.com_max-zaytsev
     name: max-zaytsev/TESTREPO

trigger:
- main

jobs:
- job: test
  timeoutInMinutes: 120
  pool:
    vmImage: macOS-12
    #name: v-mazayt-windows

  steps:
  # - powershell: |
  #     foreach($number in 1..65)
  #       {
  #         Start-Sleep -Seconds 60
  #         Write-Host "$($number * 60) seconds"
  #       }

  - checkout: MonoDroidSamples
    submodules: recursive
    fetchTags: False
    fetchDepth: 0

  - checkout: TestR
    submodules: recursive
    fetchTags: False
    fetchDepth: 0

  - script: echo Hello, world!
    displayName: 'Run a one-line script'
