variables:
  - name: System.Debug
    value: true

resources:
 repositories:
   - repository: MonoDroidSamples
     type: github
     name: xamarin/monodroid-samples
     endpoint: v-mazayt-pat-new
     #endpoint: github.com_max-zaytsev
   - repository: TestR
     type: github
     endpoint: v-mazayt-pat-new
     name: max-zaytsev/TESTREPO

trigger:
- main

jobs:
- job: test
  timeoutInMinutes: 120
  pool:
    vmImage: macOS-12
    #name: v-mazayt-windows

  steps:
  - bash: |
      sleep 62m

  - checkout: MonoDroidSamples
    submodules: recursive
    fetchTags: False
    fetchDepth: 0

  - checkout: TestR
    submodules: recursive
    fetchTags: False
    fetchDepth: 0

  - script: echo Hello, world!
    displayName: 'Run a one-line script'
