resources:
 repositories:
   - repository: xamarin
     type: github
     name: xamarin/monodroid-samples
     endpoint: v-mazayt-pat-new

trigger:
- main

pool:
  vmImage: macOS-12
  #name: v-mazayt-windows

steps:
- checkout: xamarin

- script: echo Hello, world!
  displayName: 'Run a one-line script'
